# Generated by Django 2.2.6 on 2019-10-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191004_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
